### PR TITLE
support 32-bit arguments

### PR DESCRIPTION
**Pull request by akkartik**
Before calc.asm couldn't read numbers larger than 8-bit:

  $ ./calc + 256 0
  0

Now answers should be correct until 2^32-1.

### CODE REVIEW

**Comment by flouthoc** [comment]
@akkartik Thanks a lot but i'm having some merge conflicts , can create this PR again ?

**Comment by akkartik** [comment]
I closed it?! Sorry, just messing with my fork and it had some side effect.

**Comment by akkartik** [comment]
Looks like I don't have permissions to reopen. Could you please?

**Comment by akkartik** [comment]
Never mind, I'll make another one.

**Pull request closed without merging**
